<a href="https://colab.research.google.com/github/shivraj7/numpy/blob/main/Scalar_Day40_numpy_2_24_march_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>

# Numpy-2 :24 March 2024

<img src="https://i.imgflip.com/6mv4z9.jpg" width="30%">

In [ ]:
import numpy as np

###Following section explains about masking

In [ ]:
arr = np.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Chandni
# To: Everyone
# 7:09 PM
# how to use and /or in masking
print(arr[(arr%3==0) & (arr%4==0)]) # and
print(arr[(arr%3==0) | (arr%4==0)]) # or

[12]
[ 3  4  6  8  9 12 15 16 18]


In [ ]:
arr%3==0 # mask>> arr>> bool arr> True wherever arr elemnt is divisible by 3

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [ ]:
# & >> bitwise and
# | >> bitwsie or   ## for a numpy array element level bool comparison

In [ ]:
arr%3==0 and arr%4==0 # this will give error as arr%3(arr%4) will retrun array of boolean  and 'and' needs single value not array

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
True and False

False

In [ ]:
1 and False

False

In [ ]:
bool(1), bool(0)

(True, False)

### Following section explains 'len' and 'numpy size' function difference

In [ ]:
lst = [[1,2,3],[1,2,3]]
print(lst)
print(len(lst))
arr = np.array(lst)
print(arr)
print(arr.shape)
print(arr.size)

[[1, 2, 3], [1, 2, 3]]
2
[[1 2 3]
 [1 2 3]]
(2, 3)
6


### Following section explains numpy function 'reshape'

In [ ]:
arr = np.arange(12)
print(arr)
print(arr.size) # Number of elements in the array. >> arr.shape[0]* arr.shape[1]...
print(arr.shape) # multiplying all the dimensions
print(len(arr)) # arr.shape[0]


[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
(12,)
12


In [ ]:
print(arr.reshape(3,4))
print("-"*25)
print(arr.reshape(4,3))
print("-"*25)
print(arr.reshape(6,2))
print("-"*25)
print(arr.reshape(2,6))
print("-"*25)
print(arr.reshape(12,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
-------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
-------------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
-------------------------
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [ ]:
print(arr)
print(arr.reshape(4,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


ValueError: cannot reshape array of size 12 into shape (4,4)

In [ ]:
print(arr)
print(arr.reshape(3,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


ValueError: cannot reshape array of size 12 into shape (3,2)

In [ ]:
print(arr)
print(arr.shape)
print(arr.reshape(3,-1)) # -1 for unknown dimension
print("-"*25)
print(arr.reshape(-1,2)) # -1 for unknown dimension

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
print(arr)
print(arr.shape)
print(arr.reshape(3,2, -1))# -1 for unknown dimension

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [ ]:
print(arr)
print(arr.shape)
print(arr.reshape(3,-1, -1))# -1 for unknown dimension

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


ValueError: can only specify one unknown dimension

In [ ]:
print(arr)
print(arr.shape)
print(arr.reshape(5,-1)) # -1 for unknown dimension, this will give error as as 5 is not multiple of total elements

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


ValueError: cannot reshape array of size 12 into shape (5,newaxis)

### Following section explains numpy function transpose

In [ ]:
print(arr)
print("-"*25)
arr2D = arr.reshape(4,3)
print(arr2D)
print(arr2D.shape)
print("-"*25, "TRANSPOSE")
print(arr2D.T)
print(arr2D.T.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
-------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
------------------------- TRANSPOSE
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
(3, 4)


### Accessing elements from array

In [ ]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 row:")
print(arr2D[0])
print(arr2D[1])
print(arr2D[2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 row:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 element(eg:7):")
print(arr2D[1])
print(arr2D[1][3])# arr[row_ind][col_ind]
print(arr2D[1,3])# arr[row_ind,col_ind]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 element(eg:7):
[4 5 6 7]
7
7


In [ ]:
arr1D = np.arange(12)
print(arr1D)
print("Getting 1 element(eg:7):")
print(arr1D[7])
print("Getting multiple lements:")
print(arr1D[[7,0,10,3,-1]])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Getting 1 element(eg:7):
7
Getting multiple lements:
[ 7  0 10  3 11]


In [ ]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 element(eg:7):")
print(arr2D[1,3])# arr[row_ind,col_ind]
print("Getting 1 element(eg:7):")
print(arr2D[[1],[3]])# arr[row_ind,col_ind]
print("Getting multiple lements:")
print(arr2D[[1,2,0],[3,2,1]])# arr[[row_ind],[col_ind]]>>(1,3),(2,2),(0,1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 element(eg:7):
7
Getting 1 element(eg:7):
[7]
Getting multiple lements:
[ 7 10  1]


In [ ]:
arr1D = np.arange(12)
print(arr1D)
print("Getting 1 element(eg:7):")
print(arr1D[7])
print("Getting multiple lements:")
print(arr1D[[7,0,10,3,-1]])
print("Slicing")
print(arr1D[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Getting 1 element(eg:7):
7
Getting multiple lements:
[ 7  0 10  3 11]
Slicing
[1 2]


### slicing 2d array

In [ ]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting 1 element(eg:7):")
print(arr2D[1,3])# arr[row_ind,col_ind]
print("Getting multiple lements:")
print(arr2D[[1,2,0],[3,2,1]])# arr[[row_ind],[col_ind]]>>(1,3),(2,2),(0,1)
print("Slicing")
print(arr2D[1:]) # no end is given
print("___________________")
print(arr2D[1:2]) # start=1, end=2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting 1 element(eg:7):
7
Getting multiple lements:
[ 7 10  1]
Slicing
[[ 4  5  6  7]
 [ 8  9 10 11]]
___________________
[[4 5 6 7]]


In [ ]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Getting multiple lements:")
print(arr2D[[1,2,0],[3,2,1]])# arr[[row_ind],[col_ind]]>>(1,3),(2,2),(0,1)
print("Slicing")
print(arr2D[1:]) # no end is given
print("___________________")
print(arr2D[1:2]) # start=1, end=2
print("Slicing rows and cols")
print(arr2D[1:, 0::2]) # arr[row_slicing, col_slicing]
print("get 1 col")
print(arr2D[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Getting multiple lements:
[ 7 10  1]
Slicing
[[ 4  5  6  7]
 [ 8  9 10 11]]
___________________
[[4 5 6 7]]
Slicing rows and cols
[[ 4  6]
 [ 8 10]]
get 1 col
[ 2  6 10]


In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
print(a)
print(b)
print("___________________")
print(a[3:])
print(b[::-2])
print("___________________")
a[3:] = b[::-2]
print(a)

[1, 2, 3, 4, 5]
[8, 7, 6]
___________________
[4, 5]
[6, 8]
___________________
[1, 2, 3, 6, 8]


### masking in 2d array

In [ ]:
arr1D = np.arange(12)
print(arr1D)
print("Mask")
print(arr1D%3==0)
print("Masking")
print(arr1D[arr1D%3==0])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Mask
[ True False False  True False False  True False False  True False False]
Masking
[0 3 6 9]


In [ ]:
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print("Mask")
print(arr2D%3==0)
print("Masking")
print(arr2D[arr2D%3==0]) # note that this is giving 1d array not 2d

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mask
[[ True False False  True]
 [False False  True False]
 [False  True False False]]
Masking
[0 3 6 9]


In [ ]:

# Sandeep
# To: Everyone
# 8:01 PM
# and when we have duplicate elements? it returns only distinct values?
arr2D = np.arange(12)
arr2D[:] = 3
arr2D = arr2D.reshape(3,4)
print(arr2D)
print("Mask")
print(arr2D%3==0)
print("Masking")
print(arr2D[arr2D%3==0])

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
Mask
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
Masking
[3 3 3 3 3 3 3 3 3 3 3 3]


In [ ]:
a = np.array([0,1,2,3,4,5])
print(a)
mask = (a%2 == 0)
print(mask)
print(a[mask])
a[mask] = -1
print(a)

[0 1 2 3 4 5]
[ True False  True False  True False]
[0 2 4]
[-1  1 -1  3 -1  5]


### Following section exaplain about aggreagate function

In [ ]:
# aggregate functions
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# sum
np.sum(a)

55

In [ ]:
# mean
np.mean(a)

5.0

In [ ]:
# min
np.min(a)

0

In [ ]:
# max
np.max(a)

10

In [ ]:
# median
np.median(a)

5.0

In [ ]:
# aggregate functions
a2 = np.arange(12).reshape(4,3)
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# sum
print(np.sum(a2)) #  axis=None[default]
print(np.sum(a2, axis=0)) # go along the axis=0
print(np.sum(a2, axis=1)) # go along the axis=1

66
[18 22 26]
[ 3 12 21 30]


In [ ]:
# mean
print(np.mean(a2)) #  axis=None[default]
print(np.mean(a2, axis=0)) # go along the axis=0
print(np.mean(a2, axis=1)) # go along the axis=1

5.5
[4.5 5.5 6.5]
[ 1.  4.  7. 10.]


In [ ]:
print(np.sum(a2, axis=0)) # go along the axis=0
print(np.sum(a2[:,0]))
print(np.sum(a2[:,1]))
print(np.sum(a2[:,2]))

[18 22 26]
18
22
26


In [ ]:
# python
2/1

2.0

### Logical Operators

In [ ]:
# logical operators
a = np.array([1,2,7,3,4,7,8,9,7,6,7,12])
print(a.shape)
print(a)

(12,)
[ 1  2  7  3  4  7  8  9  7  6  7 12]


In [ ]:
print(a==7) # mask
print(a[a==7]) # masking

[False False  True False False  True False False  True False  True False]
[7 7 7 7]


In [ ]:
print(a%3==0)
print(a%2==0)
# masks
print((a%3==0 )& (a%2==0)) # and
print((a%3==0 )| (a%2==0)) # or

[False False False  True False False False  True False  True False  True]
[False  True False False  True False  True False False  True False  True]
[False False False False False False False False False  True False  True]
[False  True False  True  True False  True  True False  True False  True]


In [ ]:
print(a[(a%3==0 )& (a%2==0)])

[ 6 12]


In [ ]:
print(a[(a%3==0 ) | (a%2==0)])

[ 2  3  4  8  9  6 12]


In [ ]:
print(a)

[ 1  2  7  3  4  7  8  9  7  6  7 12]


In [ ]:
# any
print("any: this will give you True if even one True is present")
print(np.any(a==7)) # is ANY value equal to 7
print(np.any(a==0)) # is ANY value equal to 0

# all
print("all: this will give you False if even one False is present")
print(np.all(a==7)) # are ALL the values equal to 7
print(np.all(a%1==0)) # are ALL the values divisible by 1

any: this will give you True if even one True is present
True
False
all: this will give you False if even one False is present
False
True


In [ ]:

# Jatin Sharma
# To: Everyone
# 8:33 PM
# can we use logical operator in any or all?
print(a)
print((a==0) | (a%4==0))
print(a[(a==0) | (a%4==0)])
print(np.any((a==0) | (a%4==0))) # is ANY value equal to 0 OR ANY value divisibke by 4

[ 1  2  7  3  4  7  8  9  7  6  7 12]
[False False False False  True False  True False False False False  True]
[ 4  8 12]
True


### Where function

In [ ]:
print(a)

[ 1  2  7  3  4  7  8  9  7  6  7 12]


In [ ]:
# where>> taken input as Mask, given indeces where mask is True
print(np.where(a==7))

(array([ 2,  5,  8, 10]),)


In [ ]:
print(a[np.where(a==7)])

[7]


In [ ]:
a2D = a.reshape(4,3)
print(a2D)

[[ 1  2  7]
 [ 3  4  7]
 [ 8  9  7]
 [ 6  7 12]]


In [ ]:
print(np.where(a2D==7))
# (array([0, 1, 2, 3]), array([2, 2, 2, 1])) >> (0,2), (1,2), (2,2), (3,1)
# (row indeces, col indeces)

(array([0, 1, 2, 3]), array([2, 2, 2, 1]))


In [ ]:
a2D[np.where(a2D==7)]

array([7, 7, 7, 7])

In [ ]:
a = np.array([0,2,3])
b = np.array([1,3,5])
print(a>=b) # element level analysis/comparison

[False False False]


In [ ]:
# in world of int, everything is True except 0
print(bool(-5))
print(bool(0))
print(bool(7))

True
False
True


In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0])
print(arr)
print(np.where(arr))

[ -3   4  27  34  -2   0 -45 -11   4   0]
(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [ ]:
# Chaitanya T
# To: Everyone
# 8:44 PM
# what if the numbers are repeated inside the array
# 8:44 PM
# 2
# Chaitanya T
# To: Everyone
# 8:45 PM
# yeah but when we pass the array as input
# Chaitanya T
# To: Everyone
# 8:45 PM
# and then when we have duplicates
# Chaitanya T
# To: Everyone
# 8:45 PM
# which indices it will throw
arr = np.array([-3,-3,-3,-3, 0, -3,-3, 0, -3])
print(arr)
print(np.where(arr))

[-3 -3 -3 -3  0 -3 -3  0 -3]
(array([0, 1, 2, 3, 5, 6, 8]),)


### Case study

In [ ]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd


Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 9.57MB/s]


In [ ]:
data = np.loadtxt("/content/fit.txt", dtype=str)

In [ ]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [ ]:
data.shape

(96, 6)

In [ ]:
date = data[:,0] # arr[row_index, col_inde]
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [ ]:
steps = data[:,1].astype(int) # arr[row_index, col_inde]
steps

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
mood = data[:,2] # arr[row_index, col_inde]
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
calories = data[:,3].astype(int) # arr[row_index, col_inde]
calories

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [ ]:
sleep = data[:,4].astype(int) # arr[row_index, col_inde]
sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [ ]:
active = data[:,5] # arr[row_index, col_inde]
active

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [ ]:
# I think I am happy when I have more steps
happy_mask = mood=="Happy"
happy_mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [ ]:
sad_mask = mood=="Sad"
sad_mask

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False, False])

In [ ]:
steps[happy_mask] # steps of days when I was happy

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [ ]:
steps[happy_mask].mean()

3392.725

In [ ]:
steps[sad_mask].mean()

2103.0689655172414

In [ ]:
# when I steps>=4000, I am mostly happy
steps4k_mask = steps>=4000
steps4k_mask

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
mood[steps4k_mask] # mood wherever steps were >=4000

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [ ]:
np.unique(mood[steps4k_mask])

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [ ]:
np.unique(mood[steps4k_mask], return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))