<a href="https://colab.research.google.com/github/shivraj7/numpy/blob/main/Scalar_Day39_numpy_3_22_march_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fitbit solution

In [ ]:
import numpy as np

In [ ]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 7.01MB/s]


In [ ]:
data = np.loadtxt('fit.txt',dtype='str')
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [ ]:
data.shape

(96, 6)

In [ ]:
data.ndim

2

In [ ]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [ ]:
#transpose of data
data.T.shape

(6, 96)

In [ ]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
a,b = (2,3)
print(a,b)

In [ ]:
date,step_count,mood,calories_burned,hours_of_sleep,activity = data.T

In [ ]:
len(date)

96

In [ ]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [ ]:
hours_of_sleep

array(['5', '8', '5', '4', '5', '6', '6', '7', '5', '6', '8', '5', '6',
       '7', '5', '6', '8', '5', '4', '5', '6', '8', '5', '6', '5', '8',
       '5', '4', '5', '4', '5', '4', '3', '2', '9', '5', '6', '4', '5',
       '8', '4', '5', '6', '5', '6', '5', '6', '5', '6', '5', '6', '7',
       '6', '7', '6', '5', '6', '7', '8', '8', '7', '8', '5', '4', '3',
       '3', '4', '5', '5', '5', '3', '4', '4', '5', '5', '5', '5', '5',
       '5', '4', '3', '4', '5', '5', '4', '5', '3', '3', '3', '2', '3',
       '2', '8', '5', '5', '5'], dtype='<U10')

In [ ]:
steps_count = np.array(step_count,dtype=int)
hours_of_sleep = np.array(hours_of_sleep,dtype=int)
calories_burned = np.array(calories_burned,dtype=int)

In [ ]:
calories_burned.astype(int)

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [ ]:
type(step_count)

numpy.ndarray

In [ ]:
int(step_count)

TypeError: only length-1 arrays can be converted to Python scalars

In [ ]:
steps_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
#avg step count
np.mean(steps_count)

2935.9375

In [ ]:
#day my step count is highest
np.max(steps_count)

7422

In [ ]:
#index values
np.argmax(steps_count)

69

In [ ]:
date[69]

'14-12-2017'

In [ ]:
date[np.argmax(steps_count)]

'14-12-2017'

In [ ]:
#alternate way
steps_count == 7422

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
date[steps_count == np.max(steps_count)]

array(['14-12-2017'], dtype='<U10')

In [ ]:
#avg step count when mood is sad
#avg step count when mood is happy
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
mood == 'Happy'

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [ ]:
np.mean(steps_count[mood == 'Happy'])

3392.725

In [ ]:
np.mean(steps_count[mood == 'Sad'])

2103.0689655172414

In [ ]:
steps_count[(mood == 'Sad') | (mood == 'Neutral')]

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,  292,
       2209, 6041,  570, 1163, 6676, 3721, 2374, 2909, 1648,  799, 7102,
       3941,  437, 1231, 1696, 4921,  221, 6500, 3575, 4061,  651,  753,
        518, 4108, 3066,  177,   36,  299, 1447, 2599,  702,  133,  500,
       2127])

#sorting

In [ ]:
a = np.array([9,3,2,5,1,6])
np.sort(a) #copy of array

array([1, 2, 3, 5, 6, 9])

In [ ]:
a

array([9, 3, 2, 5, 1, 6])

In [ ]:
a.sort() #default is asc

In [ ]:
a

array([1, 2, 3, 5, 6, 9])

In [ ]:
#desc #jugaad
a = np.array([9,3,2,5,1,6])
print(a)
a.sort()
print(a)
a[::-1]

[9 3 2 5 1 6]
[1 2 3 5 6 9]


array([9, 6, 5, 3, 2, 1])

In [ ]:
np.sort?

#sorting in 2d

In [ ]:
a = np.array([[6,2,3],[4,9,2],[8,2,1]])
a

array([[6, 2, 3],
       [4, 9, 2],
       [8, 2, 1]])

In [ ]:
a.shape

(3, 3)

In [ ]:
np.sort(a) #defult axis = 1

array([[2, 3, 6],
       [2, 4, 9],
       [1, 2, 8]])

In [ ]:
np.sort(a,axis=1)

array([[2, 3, 6],
       [2, 4, 9],
       [1, 2, 8]])

In [ ]:
a

array([[6, 2, 3],
       [4, 9, 2],
       [8, 2, 1]])

In [ ]:
np.sort(a,axis=0)

array([[4, 2, 1],
       [6, 2, 2],
       [8, 9, 3]])

In [ ]:
np.sort(a.flatten())

array([1, 2, 2, 2, 3, 4, 6, 8, 9])

In [ ]:
np.sort(a.flatten()).reshape(a.shape) #complete sorting

array([[1, 2, 2],
       [2, 3, 4],
       [6, 8, 9]])

In [ ]:
a = np.array([[6,2,3],[4,9,2],[8,2,1]])
a

array([[6, 2, 3],
       [4, 9, 2],
       [8, 2, 1]])

In [ ]:
np.sort(a,axis= None).reshape(a.shape)

array([[1, 2, 2],
       [2, 3, 4],
       [6, 8, 9]])

In [ ]:
#quiz
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])
b = np.sort(a)
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

#Element Wise operations

In [ ]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [ ]:
a+5

array([ 6,  7,  8,  9, 10])

In [ ]:
a*5

array([ 5, 10, 15, 20, 25])

In [ ]:
b = np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a+b

array([ 7,  9, 11, 13, 15])

In [ ]:
a*b

array([ 6, 14, 24, 36, 50])

In [ ]:
c = np.arange(1,4)
c

array([1, 2, 3])

In [ ]:
a+c

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
a*c

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

#2d arrays

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = np.arange(2,14).reshape(3,4)
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
a*b

array([[  0,   3,   8,  15],
       [ 24,  35,  48,  63],
       [ 80,  99, 120, 143]])

In [ ]:
c = np.arange(2,14).reshape(6,2)

In [ ]:
c

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [ ]:
a+c

ValueError: operands could not be broadcast together with shapes (3,4) (6,2) 

In [ ]:
a*c

ValueError: operands could not be broadcast together with shapes (3,4) (6,2) 

#matrix multiplication

In [ ]:
# np.dot(),np.matmul()

In [ ]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.arange(2,8).reshape(2,3)
b

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
a*b

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [ ]:
np.matmul(a,b)

array([[12, 15, 18],
       [26, 33, 40]])

In [ ]:
np.dot(a,b) #most common

array([[12, 15, 18],
       [26, 33, 40]])

In [ ]:
np.matmul(a,5) #arrays

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.dot(a,5) #array , scalar

array([[ 5, 10],
       [15, 20]])

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([3,4,5])
np.matmul(a1,a2)

26

In [ ]:
np.dot(a1,a2)

26

In [ ]:
a @ b

array([[12, 15, 18],
       [26, 33, 40]])

#Vectorization


Vectorization in NumPy refers to performing operations on entire arrays or array elements simultaneously, which is significantly faster and more efficient than using explicit loops.

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a**2 #parallel processing

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
def new_ops(x):
  if x%2 == 0:
    return x**2
  else:
    return x**3

In [ ]:
new_ops(2)

4

In [ ]:
new_ops(3)

27

In [ ]:
new_ops(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
def new_ops(x):
  if x%2 == 0:
    return x**2
  else:
    return x**3

In [ ]:
for i in a:
  # print(i)
  print(new_ops(i),end=' ')

0 1 4 27 16 125 36 343 64 729 

In [ ]:
cool_ops = np.vectorize(new_ops)

In [ ]:
cool_ops(a)

array([  0,   1,   4,  27,  16, 125,  36, 343,  64, 729])

In [ ]:
import math

In [ ]:
a = np.arange(2,11)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
math.log(64)

4.1588830833596715

In [ ]:
math.log(1000)

6.907755278982137

In [ ]:
math.log(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [ ]:
log_vect = np.vectorize(math.log)

In [ ]:
log_vect(a)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509])

#doubts

In [ ]:
a = np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(4, 3)

In [ ]:
#2d to 1d
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])